# Epistemic-Jason

This is a fork of https://github.com/MikeVezina/epistemic-jason[Michael Vezina Epistemic Jason].

= Jason
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[:outfilesuffix: .adoc]

Jason is an interpreter for an extended version of AgentSpeak. It implements the operational semantics of that language, and provides a platform for the development of multi-agent systems, with many user-customisable features. Jason is available as Open Source, and is distributed under GNU LGPL.

Jason is developed by http://jomi.das.ufsc.br[Jomi F. Hübner] and http://www.inf.pucrs.br/r.bordini[Rafael H. Bordini], based on previous work done with many colleagues, in particular Michael Fisher, Joyce Martins, Alvaro Moreira, Renata Vieira, Willem Visser, Mike Wooldridge, but also many others, as acknowledged in the manual (see the http://jason.sourceforge.net/wp/documents/[documents] page).

The Epistemic-Jason extension integrates possible worlds semantics into Jason agent programs, enabling agents to reason about their own abilities and knowledge.

As explained previously, this extension has been initially created and developed by Michael Vezina. This version is just an upgraded, maintained and clearer version of it.
You can find Mike Vezina's repo https://github.com/MikeVezina/epistemic-jason[here].

== Installation

To use the epistemic-jason extension, you will have to follow the next steps.
This section explains how to publish this version of Jason into a mavenLocal so someone can use it.

For all the projects we did in Jason, we have been using Gradle. Here the command lines will be using Gradle.

== Publish epistemic-jason in MavenLocal

The goal here is to install this jason implementation in the maven local, so you can use it as a dependency.

To do this, you need to run the following command in the root of this repo :

----
./gradlew publishToMavenLocal
----

If some tests don't pass, run :

----
./gradlew publishToMavenLocal -x test
----

To check that it has been installed correctly, you can verify that the following folder exists in your local maven repo:

    org/jason/jason/3.3-epistemic

The maven repo should be in the following folder depending on your OS:

Windows:

    C:\Users\<User_Name>\.m2

Linux:

    /home/<User_Name>/.m2

Mac:

    /Users/<user_name>/.m2

And of course, for Linux and Mac, we can write in the short form:

    ~/.m2

Once this is done, the "Installation" part is done.
Let's move on to the "Configuration" section.


== Configuration

In any Jason projects the epistemic-jason extension is needed, you will have to put the following lines in the build.gralde file :

----
dependencies {
    implementation group: 'org.jason' , name: 'jason' , version: '3.3-epistemic',
            changing: true, transitive: true
}
----

Then to use the epistemic extension in the code, the agent class must be specified as AgentEpistemic (or a subclass thereof) in the mas2j configuration file.
Further details are available in the demo repository.
